from __future__ import annotations

import json
import math
import runpy
from pathlib import Path

import numpy as np
import pandas as pd
import pyfixest as pf
from sklearn.linear_model import LogisticRegression

SEED = 20260908
np.random.seed(SEED)
OUT = Path("output_sensitivity")
OUT.mkdir(exist_ok=True)

# Re-run the frozen design generator against the exact same staged GMS marts. This creates the
# pre-declared candidate tables in one in-memory DuckDB connection and reproduces the frozen grid.
ns = runpy.run_path("tools/corporate_science_design_freeze_v1.py")
con = ns["con"]
grid = ns["grid"]

# Gate status was fixed before hypothesis estimation; only gate-passing designs enter inferential sensitivity.
passing = [x for x in grid if bool(x["passes_gate"])]

# Exact pre-trend definition used in design freeze / primary analysis.
r = pd.read_parquet("input/company_research_year.parquet", columns=["canonical_company_id", "publication_year", "work_count"])
r = r.rename(columns={"canonical_company_id": "company_id", "publication_year": "yr"})
r["company_id"] = r["company_id"].astype(str)
r["yr"] = r["yr"].astype(int)
r_lookup = {(a, int(y)): float(w) for a, y, w in r.itertuples(index=False, name=None)}

def pretrend_slope(row):
    a = r_lookup.get((str(row.company_id), int(row.entry_year) - 3), 0.0)
    b = r_lookup.get((str(row.company_id), int(row.entry_year) - 1), 0.0)
    return (math.log1p(b) - math.log1p(a)) / 2.0

ADJ = [
    "log_pre3_research_output",
    "log_pre3_research_citations",
    "pretrend_slope",
    "pre3_collab_countries",
    "pre3_network_hhi_complement",
    "pre3_network_entropy",
    "log_pre3_collab_works",
    "pre3_network_observed",
]
OUTCOME_COMMON = "z_log_pre3_research_output + z_log_pre3_research_citations + z_pretrend_slope + z_pre3_network_entropy + z_log_pre3_collab_works"
OUTCOME_COMMON_NO_ENTROPY = "z_log_pre3_research_output + z_log_pre3_research_citations + z_pretrend_slope + z_log_pre3_collab_works"
FE3 = "topic_id + company_id + entry_year"
FE_H4 = "topic_id + company_id"

def ess(w):
    w = np.asarray(w, float)
    return float((w.sum() ** 2) / np.sum(w ** 2)) if len(w) and np.sum(w ** 2) > 0 else 0.0

def wmean(x, w):
    x = np.asarray(x, float); w = np.asarray(w, float)
    return float(np.sum(w * x) / np.sum(w))

def smd(a, b, wa=None, wb=None):
    a = np.asarray(a, float); b = np.asarray(b, float)
    if wa is None:
        ma, mb = float(np.mean(a)), float(np.mean(b))
        va, vb = float(np.var(a, ddof=1)), float(np.var(b, ddof=1))
    else:
        wa = np.asarray(wa, float); wb = np.asarray(wb, float)
        ma, mb = wmean(a, wa), wmean(b, wb)
        va = float(np.sum(wa * (a - ma) ** 2) / np.sum(wa))
        vb = float(np.sum(wb * (b - mb) ** 2) / np.sum(wb))
    den = math.sqrt(max((va + vb) / 2.0, 0.0))
    return 0.0 if den == 0 else float((ma - mb) / den)

def prepare_df(tbl: str) -> tuple[pd.DataFrame, dict]:
    # Add +1..+2 output from the same company-topic mart; +3/+5 outcomes are already generated by frozen code.
    q = f"""
    SELECT p.*,
           COALESCE(SUM(CASE WHEN tt.yr BETWEEN p.entry_year+1 AND p.entry_year+2
                             THEN tt.work_count ELSE 0 END),0) AS post2_topic_output
    FROM {tbl} p
    LEFT JOIN t tt
      ON tt.company_id=p.company_id AND tt.topic_id=p.topic_id
     AND tt.yr BETWEEN p.entry_year+1 AND p.entry_year+2
    GROUP BY ALL
    """
    d = con.execute(q).df()
    d["company_id"] = d["company_id"].astype(str)
    d["topic_id"] = d["topic_id"].astype(str)
    d["entry_year"] = d["entry_year"].astype(int)
    d["sic2"] = d["sic"].astype(str).str.extract(r"(\d{2})", expand=False).fillna("UNK")
    d["pretrend_slope"] = d.apply(pretrend_slope, axis=1)
    d["log_pre3_research_output"] = np.log1p(pd.to_numeric(d["pre3_research_output"], errors="coerce").fillna(0))
    d["log_pre3_research_citations"] = np.log1p(pd.to_numeric(d["pre3_research_citations"], errors="coerce").fillna(0))
    d["log_pre3_collab_works"] = np.log1p(pd.to_numeric(d["pre3_collab_works"], errors="coerce").fillna(0))
    d["y_h1_2"] = np.log1p(pd.to_numeric(d["post2_topic_output"], errors="coerce").fillna(0))
    d["y_h1_3"] = np.log1p(pd.to_numeric(d["post3_topic_output"], errors="coerce").fillna(0))
    d["y_h1_5"] = np.log1p(pd.to_numeric(d["post5_topic_output"], errors="coerce"))
    d["y_h2_3"] = pd.to_numeric(d["active_at_plus3"], errors="coerce")
    d["y_h2_5"] = pd.to_numeric(d["active_at_plus5"], errors="coerce")
    d["y_h3_3"] = np.log1p(pd.to_numeric(d["post3_field_year_norm_citation_ratio"], errors="coerce"))

    for c in ADJ:
        x = pd.to_numeric(d[c], errors="coerce")
        med = float(x.median()) if x.notna().any() else 0.0
        x = x.fillna(med)
        sd = float(x.std(ddof=0))
        d[c] = x
        d["z_" + c] = (x - float(x.mean())) / sd if sd > 0 else 0.0

    Xc = d[["z_" + c for c in ADJ]].to_numpy(float)
    Xd = pd.get_dummies(d["sic2"], prefix="sic2", dtype=float)
    X = np.column_stack([Xc, Xd.to_numpy(float)])
    y = d["early_entry"].astype(int).to_numpy()
    ps = LogisticRegression(C=1.0, max_iter=10000, solver="lbfgs", random_state=SEED).fit(X, y).predict_proba(X)[:, 1]
    ps = np.clip(ps, 0.03, 0.97)
    d["propensity"] = ps
    d["overlap_weight"] = np.where(y == 1, 1 - ps, ps)
    d["overlap_weight"] /= d["overlap_weight"].mean()

    e = d[d.early_entry == 1]; l = d[d.early_entry == 0]
    weighted_smds = [smd(e[c], l[c], e.overlap_weight, l.overlap_weight) for c in ADJ]
    diag = {
        "ess": ess(d.overlap_weight),
        "max_abs_weighted_smd": float(max(abs(x) for x in weighted_smds)),
        "propensity_min": float(ps.min()),
        "propensity_max": float(ps.max()),
        "balance_ok_0_10": bool(max(abs(x) for x in weighted_smds) <= 0.10),
    }
    return d, diag

def extract(fit, param: str) -> dict:
    co = fit.coef()
    if param not in list(co.index):
        return {"status": "not_identified", "n": int(getattr(fit, "_N", 0)), "dropped": list(getattr(fit, "_collin_vars", []))}
    return {
        "status": "identified",
        "n": int(getattr(fit, "_N", 0)),
        "estimate": float(fit.coef().loc[param]),
        "se": float(fit.se().loc[param]),
        "p": float(fit.pvalue().loc[param]),
        "dropped": list(getattr(fit, "_collin_vars", [])),
    }

def fit_model(formula: str, param: str, d: pd.DataFrame, weighted=True, crv3=False) -> dict:
    kw = {"data": d, "fixef_rm": "singleton", "collin_tol": 1e-9}
    if weighted:
        kw.update({"weights": "overlap_weight", "weights_type": "aweights"})
    out = {}
    for name, vcov in [
        ("topic_crv1", {"CRV1": "topic_id"}),
        ("two_way_crv1", {"CRV1": "topic_id + company_id"}),
    ] + ([ ("topic_crv3", {"CRV3": "topic_id"}) ] if crv3 else []):
        try:
            out[name] = extract(pf.feols(formula, vcov=vcov, **kw), param)
        except Exception as exc:
            out[name] = {"status": "failed", "error": f"{type(exc).__name__}: {exc}"}
    return out

def supported_subset(d: pd.DataFrame, outcome: str, min_n=50, min_topics=15) -> tuple[pd.DataFrame, dict]:
    x = d[d[outcome].notna()].copy()
    if x.empty:
        return x, {"n": 0, "topics": 0, "support_ok": False}
    s = x.groupby("topic_id")["early_entry"].agg(["min", "max"])
    valid = s[(s["min"] == 0) & (s["max"] == 1)].index
    x = x[x.topic_id.isin(valid)].copy()
    return x, {"n": int(len(x)), "topics": int(x.topic_id.nunique()), "support_ok": bool(len(x) >= min_n and x.topic_id.nunique() >= min_topics)}

rows = []
details = {}
for g in passing:
    spec = str(g["emergence_spec"])
    w = int(g["early_window"])
    tbl = f"p_{spec}_w{w}"
    d, balance = prepare_df(tbl)
    key = f"{spec}_w{w}"

    # Same final primary estimator family as inference-hardened checkpoint.
    h1_3 = fit_model(f"y_h1_3 ~ early_entry + {OUTCOME_COMMON} | {FE3}", "early_entry", d, weighted=True)
    h2_3 = fit_model(f"y_h2_3 ~ early_entry + {OUTCOME_COMMON} | {FE3}", "early_entry", d, weighted=True)
    h4 = fit_model(f"early_entry ~ z_pre3_network_entropy + {OUTCOME_COMMON_NO_ENTROPY} | {FE_H4}", "z_pre3_network_entropy", d, weighted=False)
    h5_3 = fit_model(f"y_h2_3 ~ early_entry * z_pre3_network_entropy + {OUTCOME_COMMON_NO_ENTROPY} | {FE3}", "early_entry:z_pre3_network_entropy", d, weighted=True, crv3=True)

    # Pre-frozen outcome-window sensitivity. H1 can vary accumulation window; H2/H5 remain persistence at +3/+5.
    h1_2 = fit_model(f"y_h1_2 ~ early_entry + {OUTCOME_COMMON} | {FE3}", "early_entry", d, weighted=True)
    d5, s5 = supported_subset(d, "y_h1_5")
    if s5["support_ok"]:
        h1_5 = fit_model(f"y_h1_5 ~ early_entry + {OUTCOME_COMMON} | {FE3}", "early_entry", d5, weighted=True)
        h2_5 = fit_model(f"y_h2_5 ~ early_entry + {OUTCOME_COMMON} | {FE3}", "early_entry", d5, weighted=True)
        h5_5 = fit_model(f"y_h2_5 ~ early_entry * z_pre3_network_entropy + {OUTCOME_COMMON_NO_ENTROPY} | {FE3}", "early_entry:z_pre3_network_entropy", d5, weighted=True, crv3=True)
    else:
        h1_5 = h2_5 = h5_5 = {"support": s5, "status": "insufficient_complete_followup_support"}

    # H3 remains conditional on continued output and obeys the frozen minimum support rule.
    d3 = d[d["y_h3_3"].notna()].copy()
    s3 = d3.groupby("topic_id")["early_entry"].agg(["min", "max"]) if len(d3) else pd.DataFrame()
    valid3 = s3[(s3["min"] == 0) & (s3["max"] == 1)].index if len(s3) else []
    d3 = d3[d3.topic_id.isin(valid3)].copy() if len(d3) else d3
    h3_support = {"n": int(len(d3)), "topics": int(d3.topic_id.nunique()), "support_passed": bool(len(d3) >= 30 and d3.topic_id.nunique() >= 8)}

    def pick(model, vcov="topic_crv1"):
        rr = model.get(vcov, {}) if isinstance(model, dict) else {}
        return rr.get("estimate"), rr.get("p"), rr.get("status")

    h1e, h1p, _ = pick(h1_3)
    h2e, h2p, _ = pick(h2_3)
    h4e, h4p, _ = pick(h4)
    h5e, h5p, _ = pick(h5_3)
    _, h5tw, _ = pick(h5_3, "two_way_crv1")
    _, h5c3, _ = pick(h5_3, "topic_crv3")

    row = {
        "design": key,
        "emergence_spec": spec,
        "early_window": w,
        "episodes": int(len(d)),
        "topics": int(d.topic_id.nunique()),
        "firms": int(d.company_id.nunique()),
        "early": int(d.early_entry.sum()),
        "later": int((1-d.early_entry).sum()),
        **balance,
        "h1_post3_est": h1e, "h1_post3_p_topic": h1p,
        "h2_plus3_est": h2e, "h2_plus3_p_topic": h2p,
        "h4_entropy_est": h4e, "h4_entropy_p_topic": h4p,
        "h5_plus3_est": h5e, "h5_plus3_p_topic": h5p,
        "h5_plus3_p_twoway": h5tw, "h5_plus3_p_crv3": h5c3,
        "h3_supported_n": h3_support["n"], "h3_supported_topics": h3_support["topics"], "h3_support_passed": h3_support["support_passed"],
        "plus5_support_n": s5["n"], "plus5_support_topics": s5["topics"], "plus5_support_ok": s5["support_ok"],
    }
    for label, model in [("h1_post2", h1_2), ("h1_post5", h1_5), ("h2_plus5", h2_5), ("h5_plus5", h5_5)]:
        if isinstance(model, dict) and "topic_crv1" in model:
            est, p, _ = pick(model)
            row[label + "_est"] = est
            row[label + "_p_topic"] = p
        else:
            row[label + "_est"] = None
            row[label + "_p_topic"] = None

    rows.append(row)
    details[key] = {
        "gate_row": g,
        "selection_balance": balance,
        "H1_post2": h1_2,
        "H1_post3": h1_3,
        "H1_post5": h1_5,
        "H2_plus3": h2_3,
        "H2_plus5": h2_5,
        "H3_support": h3_support,
        "H4": h4,
        "H5_plus3": h5_3,
        "H5_plus5": h5_5,
        "plus5_support": s5,
    }

res = pd.DataFrame(rows).sort_values(["emergence_spec", "early_window"]).reset_index(drop=True)
res.to_csv(OUT / "sensitivity_results.csv", index=False)
(OUT / "sensitivity_details.json").write_text(json.dumps(details, indent=2), encoding="utf-8")

balanced = res[res.balance_ok_0_10 == True].copy()
def sign_summary(col, expected_positive=True):
    x = pd.to_numeric(balanced[col], errors="coerce").dropna()
    if not len(x): return {"n": 0}
    return {
        "n": int(len(x)),
        "positive_share": float((x > 0).mean()),
        "negative_share": float((x < 0).mean()),
        "median_estimate": float(x.median()),
        "min_estimate": float(x.min()),
        "max_estimate": float(x.max()),
    }

summary = {
    "status": "FROZEN_SENSITIVITY_COMPLETE",
    "predeclared_gate_passing_designs": int(len(passing)),
    "balanced_gate_passing_designs": int(len(balanced)),
    "balance_rule": "max absolute weighted SMD <= 0.10 on genuine pre-entry covariates",
    "H1_post3_signs": sign_summary("h1_post3_est"),
    "H2_plus3_signs": sign_summary("h2_plus3_est"),
    "H4_signs": sign_summary("h4_entropy_est"),
    "H5_plus3_signs": sign_summary("h5_plus3_est"),
    "H1_post2_signs": sign_summary("h1_post2_est"),
    "H1_post5_signs": sign_summary("h1_post5_est"),
    "H2_plus5_signs": sign_summary("h2_plus5_est"),
    "H5_plus5_signs": sign_summary("h5_plus5_est"),
    "H5_plus3_topic_p_lt_005_share": float((pd.to_numeric(balanced.h5_plus3_p_topic, errors="coerce") < 0.05).mean()),
    "H5_plus3_twoway_p_lt_005_share": float((pd.to_numeric(balanced.h5_plus3_p_twoway, errors="coerce") < 0.05).mean()),
    "H5_plus3_crv3_p_lt_010_share": float((pd.to_numeric(balanced.h5_plus3_p_crv3, errors="coerce") < 0.10).mean()),
    "H3_support_passed_designs": int(balanced.h3_support_passed.sum()),
    "primary_design": "p2_100_w2",
    "interpretation": "associational sensitivity only; no specification selected after outcomes; failed feasibility designs excluded from inference",
}
(OUT / "sensitivity_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

md = []
md.append("# Corporate Science Entry — Frozen Sensitivity Analysis")
md.append("")
md.append("This checkpoint applies the pre-frozen emergence/entry-window grid to the exact same GMS release. Only designs that passed the feasibility gate before hypothesis estimation are used inferentially.")
md.append("")
md.append(f"- Gate-passing designs tested: **{len(passing)}**.")
md.append(f"- Designs also meeting post-weight balance ≤0.10 SMD: **{len(balanced)}**.")
md.append("- Primary design remains **p2_100 / early window 0–2**; no sensitivity result replaces it.")
md.append("")
md.append("## H1/H2/H4/H5 across gate-passing designs")
md.append("")
md.append("| Design | N | Topics | Max wSMD | H1 +3 est | H2 +3 est | H4 est | H5 +3 est | H5 p(topic) | H5 p(two-way) | H5 p(CRV3) |")
md.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
for _, x in res.iterrows():
    def f(v): return "NA" if pd.isna(v) else f"{float(v):.3f}"
    md.append(f"| {x.design} | {int(x.episodes)} | {int(x.topics)} | {f(x.max_abs_weighted_smd)} | {f(x.h1_post3_est)} | {f(x.h2_plus3_est)} | {f(x.h4_entropy_est)} | {f(x.h5_plus3_est)} | {f(x.h5_plus3_p_topic)} | {f(x.h5_plus3_p_twoway)} | {f(x.h5_plus3_p_crv3)} |")
md.append("")
md.append("## Sign stability")
for k in ["H1_post3_signs", "H2_plus3_signs", "H4_signs", "H5_plus3_signs", "H1_post2_signs", "H1_post5_signs", "H2_plus5_signs", "H5_plus5_signs"]:
    md.append(f"- {k}: `{json.dumps(summary[k])}`")
md.append("")
md.append(f"- H5 +3 topic-CRV1 p<0.05 share: **{summary['H5_plus3_topic_p_lt_005_share']:.1%}**.")
md.append(f"- H5 +3 two-way p<0.05 share: **{summary['H5_plus3_twoway_p_lt_005_share']:.1%}**.")
md.append(f"- H5 +3 topic-CRV3 p<0.10 share: **{summary['H5_plus3_crv3_p_lt_010_share']:.1%}**.")
md.append(f"- H3 frozen support rule passes in **{summary['H3_support_passed_designs']}** balanced sensitivity designs; primary H3 remains unresolved regardless.")
md.append("")
md.append("## Outcome-window discipline")
md.append("- H1 uses +1..+2, +1..+3 (primary), and +1..+5 where complete.")
md.append("- H2 and H5 persistence use +3 (primary) and +5 where complete; H2 is not redefined as +2 persistence.")
md.append("- H3 is never forced when within-topic early/later support is below its frozen minimum.")
md.append("")
md.append("## Interpretation rule")
md.append("The sensitivity grid is used to assess stability, not to choose the most favorable coefficient. Failed feasibility designs are not mined for inference. Any H5 conclusion remains associational and must reflect both sign stability and small-cluster inference sensitivity from the prior hardened checkpoint.")
(OUT / "SENSITIVITY_ANALYSIS.md").write_text("\n".join(md) + "\n", encoding="utf-8")

print(json.dumps(summary, indent=2))
